app:
  notifications: twilio # or change to mailgun

mailgun:
  domain: mailgundomain.example.org
  apiKey: abcd1234
  from:
    address: test@example.com
    display: StubSpy Alert
  to: john.doe@example.com

twilio:
  from: +12125550000
  to: +12125551234
  authToken: aaaaa123
  accountSid: bbbbb456

stubhub:
  token: xyz9999

alerts:
-
  stubhub:
    enabled: true
    eventId: 103577617 # Dolphins @ Bills 12/30/2018
    zoneId: 2733 # Club sections
  ticketmasterResale:
    enabled: true
    eventId: 00005467B0618E66 # Dolphins @ Bills 12/30/2018
    sections:
    - 206
    - 207
    - 208
  quantity: 2
  rows:
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  eventName: Bills vs Dolphins
  maxPrice: 180
  dailySummary: true # Not currently implemented
  instantAlert: true

debug: true

logging:
  file: logs/app.log
  level:
    root: info
    org.pulcini.stubspy: debug
